### ISSUE TITLE
Clean up & list of small fixes

### ISSUE THREAD

**Issue by fijam** [fijam/gmdrec#18]
This is for tracking smaller refactors which do not need their own ticket

- [x] sometimes we use string concatenation, at other times f-strings, sometimes both (esp. `webapi.py` and `spot.py`)
- [x] add [japanese brackets](https://en.wikipedia.org/wiki/List_of_Japanese_typographic_symbols#Brackets_and_quotation_marks) to letter-replacement lookup function, at least _kagi_「」
- [x] clean up letter replace to return immediately on hit
- [x] move PRESS and HOLD to per-device hardware definitions, relax a bit for R55/R37
- [x] get rid of OFFSET
- [x] zip (?) eeprom values with wipers dictionary
- [x] add VolUp to hardware.py cause I forgot
- [x] `hardware.py` is not really about hardware... make current digipot to be hardware and rename it something else like logic
- [x] move more stuff from `mdrec.py` to logic
- [x] move eeprom stuff and calibration loading to hardware
